### ISSUE TITLE
question re piaware software install

### ISSUE THREAD

**Issue by daviddnsw** [tti0/piaware_blinkt#1]
can the code pick-up the required info from a local package install of the piaware software as opposed to a setup with the rpi image?

(from the code i see the grab.sh ?copies/clones the status.json file so the code can read it
the software install version of piaware running on raspbian doesnt seem to have an equivalent file??)

**Comment by tti0** [comment]
Indeed, this software was developed using the SD card image of Pi Aware.

Is there not a web server running with the packaged software, showing the status of the Pi Aware system, on port 80?

This software is more of a "bodge", grabbing the data used by the web server, not from the Pi Aware applications themselves (PiAware, FlightAware, MLAT, etc.).

Please let me know if you find anything more out.

In any case, I will add a note in the README about this.

**Comment by daviddnsw** [comment]
i found a file at path /run/piaware/status.json
when i try to edit grab.sh and run i get a permission denied error??

**Comment by tti0** [comment]
This is to be expected, as `/run/piaware/status.json` is not available over a web server, which grab.sh uses. Try editing line 12 of https://github.com/tti0/piaware_blinkt/blob/master/piaware_blinkt.py to:
```
with open('/run/piaware/status.json') as json_data:
```
and ignore everything to do with `grab.sh`. Just run the Python script as root (root perms are needed to access GPIOs for the Blinkt)

**Comment by daviddnsw** [comment]
success, the leds illuminate!
is the python script looping to check any changes or does it output based on status at execution?

**Comment by tti0** [comment]
I've now fixed this issue permanently in commit aff06bf713c9faa5c71eeb2307a9b23a6212b563. Please follow the instructions in the README from scratch.

Yes, the Python script checks the `status.json` every 3 seconds for changes, and updates the LEDs accordingly. The script runs in the background started on boot, as in `/etc/rc.local` as in the instructions.

Do let me know if there are any other issues - it seems the PiAware software has been changed slightly since I last updated this project.
